#!/usr/bin/env python3
"""Generate unitree_mujoco simulate_python/config.py from environment variables."""

from __future__ import annotations

import os
from pathlib import Path

ROBOT = os.environ.get("AGRO_ROBOT", "go2").lower()
SCENE = os.environ.get("AGRO_MJ_SCENE", "")
USE_JOYSTICK = os.environ.get("AGRO_USE_JOYSTICK", "0") == "1"
ELASTIC_BAND = os.environ.get("AGRO_ELASTIC_BAND", "1" if ROBOT == "g1" else "0") == "1"

if not SCENE:
    SCENE = "../unitree_robots/go2/scene.xml" if ROBOT == "go2" else "../unitree_robots/g1/scene_29dof.xml"

config_path = Path(os.environ.get("UNITREE_MUJOCO_DIR", "/opt/unitree_mujoco")) / "simulate_python/config.py"

content = f'''# Auto-generated by AgroKit — do not edit manually.
ROBOT = "{ROBOT}"
ROBOT_SCENE = "{SCENE}"
DOMAIN_ID = 1
INTERFACE = "lo"
PRINT_SCENE_INFORMATION = False

USE_JOYSTICK = {1 if USE_JOYSTICK else 0}
JOYSTICK_TYPE = "xbox"
JOYSTICK_DEVICE = 0

ENABLE_ELASTIC_BAND = {str(ELASTIC_BAND)}
SIMULATE_DT = 0.003
VIEWER_DT = 0.02
'''

config_path.write_text(content)
print(f"[configure_mujoco] wrote {config_path} (robot={ROBOT})")
